---
title: "Visualize Digitized space that pollen occupies"
author: "Callin Switzer"
date: "February 10, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/callinswitzer/Dropbox/ExperSummer2016/Kalmia/Manuscript/DatasetsSupplemental/KalmiaDigitizedPolygon/")
```



<pre>
## import polygons of pollen area that were digitzed with matlab
## align them and plot them 
</pre>

### Read in metadata, and prep for video processing




```{r}
# session Info
sessionInfo()

#set wd
setwd("/Users/callinswitzer/Dropbox/ExperSummer2016/Kalmia/Manuscript/DatasetsSupplemental/KalmiaDigitizedPolygon/")

# get files with polygon coordinates
polyFiles <- dir()[grep(dir(), pattern = "_polygon.txt") ]

## read in files, and make into a long dataframe 
## remove last 9 points which contain metadata

for(ii in 1:length(polyFiles)){
     tmp <- read.csv(polyFiles[ii])
     #read in X and Y as vectors -- these are the four points on the flower for reference
     
     # rotate polygons
     X = tmp$xvals
     Y = 600-tmp$yvals #flip coordinates, because MATLAB is opposite of R
     M <- cbind(X,Y)

     #calculate rotation angle to make all flowers upright
     x1 <- M[(length(X) - 7),1 ]
     y1 <- M[(length(Y) - 7), 2 ]
     x2 <- M[(length(X)-5),1 ]
     y2 <- M[(length(Y)-5),2 ]

     alpha <- -atan((y1-y2)/(x1-x2)) + pi/2
     #rotation matrix
     rotm <- matrix(c(cos(alpha),sin(alpha),-sin(alpha),cos(alpha)),ncol=2)
     
     #shift points, so that turning point is (0,0)
     M2.1 <- t(t(M)-c(x1,y1))
     
     #rotate
     M2.2 <- t(rotm %*% (t(M2.1)))

     x12 <- M2.2[(length(X) - 7),1 ]
     y12 <- M2.2[(length(Y) - 7), 2 ]
     x22 <- M2.2[(length(X)-5),1 ]
     y22 <- M2.2[(length(Y)-5),2 ]
     
     ## make sure that the points aren't upside down (rotate 180 degrees, if necessary)
     if(y22 > y12){
          alpha <-  pi
          #rotation matrix
          rotm <- matrix(c(cos(alpha),sin(alpha),-sin(alpha),cos(alpha)),ncol=2)
          M2.2 <- t(rotm %*% (t(M2.2)))
     }
     
     # scale so that length between center of flower and pocket is 1
     x13 <- M2.2[(length(X) - 8),1 ]
     y13 <- M2.2[(length(Y) - 8), 2 ]
     x23 <- M2.2[(length(X)-7),1 ]
     y23 <- M2.2[(length(Y)-7),2 ]
     
     # find distance and normalize size
     dst <- sqrt((x13-x23)^2 + (y13 -y23)^2)
     
     M2.3 <- M2.2 / dst
     
     tmp <- as.data.frame(M2.3[1:(nrow(M2.3) - 9),])
     tmp$rec = substr(polyFiles[ii], start = 1, stop = 15)
     if(ii == 1) tmp2 <- tmp
     else tmp2 <- rbind(tmp, tmp2)
     
     # visualize polygons on top of each other
     if (ii == 1){
          plot(tmp[, 1], tmp[,2], type = 'n', xlim = c(-3,3), ylim = c(-1, 5))
          polygon(tmp[, 1], tmp[,2], col = rgb(0,0,1,0.05), border = NA)

     } 
     else {
          ## To flip horizontaly ,randomly
          tmp[,1] <- sample(x = c(1, -1), size = 1) * tmp[,1]
          polygon(tmp[, 1], tmp[,2], col = rgb(0,0,1,0.05), border = NA)
     }
     #Sys.sleep(0.1)
}

```


```{r, eval = FALSE}
# same thing, except save as images
# these images will be used in python to create a 3D representation

for(ii in 1:length(polyFiles)){
     tmp <- read.csv(polyFiles[ii])
     #read in X and Y as vectors -- these are the four points on the flower for reference
     # rotate polygons
     X = tmp$xvals
     Y = 600-tmp$yvals
     M <- cbind(X,Y)

     #calculate rotation angle
     x1 <- M[(length(X) - 7),1 ]
     y1 <- M[(length(Y) - 7), 2 ]
     x2 <- M[(length(X)-5),1 ]
     y2 <- M[(length(Y)-5),2 ]

     alpha <- -atan((y1-y2)/(x1-x2)) + pi/2
     #rotation matrix
     rotm <- matrix(c(cos(alpha),sin(alpha),-sin(alpha),cos(alpha)),ncol=2)
     
     #shift points, so that turning point is (0,0)
     M2.1 <- t(t(M)-c(x1,y1))

     #rotate
     M2.2 <- t(rotm %*% (t(M2.1)))
     # polygon(M2.2,col="green")
     x12 <- M2.2[(length(X) - 7),1 ]
     y12 <- M2.2[(length(Y) - 7), 2 ]
     x22 <- M2.2[(length(X)-5),1 ]
     y22 <- M2.2[(length(Y)-5),2 ]
     
     ## make sure that the points aren't upside down (rotate 180 degrees, if necessary)
     if(y22 > y12){
          alpha <-  pi
          #rotation matrix
          rotm <- matrix(c(cos(alpha),sin(alpha),-sin(alpha),cos(alpha)),ncol=2)
          M2.2 <- t(rotm %*% (t(M2.2)))
     }
     
     # scale so that length between center of flower and pocket is 1
     x13 <- M2.2[(length(X) - 8),1 ]
     y13 <- M2.2[(length(Y) - 8), 2 ]
     x23 <- M2.2[(length(X)-7),1 ]
     y23 <- M2.2[(length(Y)-7),2 ]

     # find distance 
     dst <- sqrt((x13-x23)^2 + (y13 -y23)^2)
     
     M2.3 <- M2.2 / dst
     
     tmp <- as.data.frame(M2.3[1:(nrow(M2.3) - 9),])
     tmp$rec = substr(polyFiles[ii], start = 1, stop = 15)
     if(ii == 1) tmp2 <- tmp
     else tmp2 <- rbind(tmp, tmp2)
     
     
     # plot polygon and save
     # save as high resolution 
     # note: I'll lower resolution later in Python
     png( paste0(tmp$rec, 'TEST.png'), width = 2000, height = 2000)
     par(mai=c(0,0,0,0))
     par( mgp = c(0, -1.4, 0)  )
     par(tcl = 0.5)

     plot(tmp[, 1], tmp[,2], type = 'n', xlim = c(-4,4), ylim = c(-1, 7), 
          asp=1, ann=FALSE, bty = 'n')
     polygon(tmp[, 1], tmp[,2], col = rgb(0,0,1,1), border = NA)
     #lines(x = c(.1,.1, -.1, -.1, .1, -1, 1), y = c(0, -.5, 0, -.5, 0,0, 0))
     abline(h = 0, v = c(0, 1, -1))
     dev.off()
}

```






