---
title: "Analyze pollinators and behaviors"
author: "Callin Switzer"
date: "February 10, 2017"
output: html_document
---

<pre>
# Callin Switzer
# 9 Nov 2016
# update 10 Feb 2017
## Analyze the behavior of pollinators
## from videos that I manually classified
</pre>


### Setup

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = "/Users/callinswitzer/Dropbox/ExperSummer2016/Kalmia/Manuscript/DatasetsSupplemental/")
```

```{r, message = FALSE, warning=FALSE}
# set seed so every run is the same
set.seed(123)
ipak <- function(pkg){
     new.pkg <- pkg[!(pkg %in% installed.packages()[, "Package"])]
     if(length(new.pkg)) install.packages(new.pkg, dependencies = TRUE)
     sapply(pkg, require, character.only = TRUE)
}

packages <- c("ggplot2", "gsheet", 'lme4', 'plyr', 'nnet', 'viridis')
ipak(packages)

# set ggplot theme
theme_set(theme_classic() + theme(axis.text = element_text(colour = 'black')))
```


## Read in data
```{r}
# gsheet called Kalmia Bee Behavior classification
# URL = 'https://docs.google.com/spreadsheets/d/1gxAmCcwJ9zsnYxjXe2hnTowPUxTjadbBx-eXJYS4_Js/edit?usp=sharing'

setwd("/Users/callinswitzer/Dropbox/ExperSummer2016/Kalmia/Manuscript/DatasetsSupplemental/")

# set directory for saving files
figDir = '/Users/callinswitzer/Dropbox/ExperSummer2016/Kalmia/Manuscript/Media/'

# import data
beh = read.csv('KalmiaInsectVisitors.csv')

# discard some messed up data (labeled as discard in the dataset)
discRows = grep(pattern = 'discard', 
                x = tolower(apply(beh, 
                         MARGIN = 1, 
                         FUN = paste0, collapse = "_")))
beh = beh[-discRows, ]

# remove lab views with captive bees
beh_field <-beh[beh$vid.type == 'field',]


# visualize diversity of pollinators
unique(beh_field$pollinatorClass)

# set order of levels
beh_field <- within(beh_field, 
                    pollinatorClass <- factor(pollinatorClass, 
                            levels=names(sort(table(pollinatorClass), 
                                              decreasing=TRUE))))
nrow(beh_field) # total number of videos from field
```

### Visualize pollinators
```{r}
quartz()
ggplot(beh_field, aes(x = pollinatorClass)) + 
     geom_bar() + 
     labs (x = "Insect visitor", y = "Frequency") +
     theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1,colour = 'black'), 
           axis.ticks.x=element_blank()) + 
     scale_x_discrete(labels=c("Bombus spp." = expression(
          paste(italic("Bombus spp."))), 
          "Xylocopa virginica" = expression(
               paste(italic("Xylocopa virginica"))),
          "Apis mellifera" = expression(
               paste(italic("Apis mellifera")))))
ggsave(filename = paste0(figDir, "Supp_VisitorProps.pdf"), width = 5, height = 4)
```


# Make proportion figure
```{r}
propTab <- data.frame(prop.table(table(beh_field$pollinatorClass)))
names(propTab) = c("Insect", "Proportion")
propTab # supplemental table -- proportion
Tab <- data.frame((table(beh_field$pollinatorClass)))
names(Tab) = c("Insect", "Count")
Tab # supplemental table -- count


# resample proportion table to get error bars
resTab <- function(o){
     prop.table(table(sample(beh_field$pollinatorClass, replace = TRUE)))
}

reps <- t(replicate(10000, resTab()))
colMeans(as.matrix(reps))
# get 95% CI's
propTab <- cbind(propTab, t(apply(reps, MARGIN = 2, quantile, c(0.025, 0.975))))
propTab
names(propTab)[3:4] <- c("lower", "upper")

# for(ii in 1:6){
#     print(prop.test(table(beh_field$pollinator)[ii], nrow(beh_field)))
# }

nrow(beh_field)
quartz()
ggplot(propTab, aes(x = Insect, y = Proportion)) + 
     #geom_bar(stat = 'identity') + 
     geom_point(size = 1, color= 'grey40') + 
     geom_pointrange(aes(ymax = upper, ymin=lower), size = 0.2) + 
     labs (x = "Insect visitor", y = "Proportion of visits") +
     ylim(c(0,1)) + 
     theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1, colour = 'black'), 
           axis.ticks.x=element_blank()) + 
     scale_x_discrete(labels=c("Bombus spp." = expression(
          paste(italic("Bombus spp."))), 
          "Xylocopa virginica" = expression(
               paste(italic("Xylocopa virginica"))),
          "Apis mellifera" = expression(
               paste(italic("Apis mellifera")))))
ggsave(filename = paste0(figDir,"Supp_VisitorProps2.pdf"), width = 5, height = 4)
```



### Investigate behaviors that triggered anthers

```{r}
beh_trig <- beh_field[!(is.na(beh_field$timeTrig1)), ]
beh_trig <- droplevels(beh_trig)

propTab2 <- data.frame(prop.table(table(beh_trig$pollinatorClass)))
names(propTab2) = c("Insect", "Proportion")
propTab2 # not really an accurate representation

# this is just a count of number of pollinators that triggered an anther
CT2 <- data.frame((table(beh_trig$pollinatorClass)))
names(CT2) = c("Insect", "Count")
CT2 # not really an accurate representation



# resample proportion table to get error bars
resTab2 <- function(o){
     prop.table(table(sample(beh_trig$pollinatorClass, replace = TRUE)))
}

reps <- t(replicate(10000, resTab2()))
colMeans(as.matrix(reps))
# get 95% CI's
propTab2 <- cbind(propTab2, t(apply(reps, MARGIN = 2, quantile, c(0.025, 0.975))))
propTab2
names(propTab2)[3:4] <- c("lower", "upper")


#quartz()
ggplot(propTab2, aes(x = Insect, y = Proportion)) + 
     geom_point(size = 1, color= 'grey40') + 
     geom_pointrange(aes(ymax = upper, ymin=lower), size = 0.2) + 
     labs (x = "Insect visitor", y = "Proportion of visitors\nthat triggered anthers") +
     theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1, colour = 'black'), 
           axis.ticks.x=element_blank()) + 
     scale_x_discrete(labels=c("Bombus spp." = expression(
          paste(italic("Bombus spp."))), 
          "Xylocopa virginica" = expression(
               paste(italic("Xylocopa virginica"))),
          "Apis mellifera" = expression(
               paste(italic("Apis mellifera")))))
ggsave(filename = paste0(figDir,"Supp_VisitorTrig.pdf"), width = 4, height = 4)
nrow(beh_trig) # total insects that triggered an anther in the field
```

## What behaviors resulted in catapult release
```{r, cache = TRUE}

######################################################################
## Describe what bumblebee behaviors resulted in anther triggers
######################################################################

# make a long dataset
newDF <- data.frame()
for(ii in beh$Video){
     tmp  = beh[beh$Video == ii , ]
     tmp_long <- reshape(tmp, varying = c("timeTrig1"    , "trigBehavior1" , "trigLeg1"     ,
                                          "timeTrig2",      "trigBehavior2",  "trigLeg2"   ,
                                          "timeTrig3"   ,  "trigBehavior3" , "trigLeg3"   ,
                                          "timeTrig4" ,     "trigBehavior4" , "trigLeg4"   ,
                                          "timeTrig5" ,    "trigBehavior5" , "trigLeg5"), 
             direction = 'long', 
             idvar = "Video", sep = "")
     
     tmp_long <- tmp_long[!(is.na(tmp_long$timeTrig)), ]
     newDF <- rbind(tmp_long, newDF)
}

# make new factors
newDF$Beh2 <- mapvalues(newDF$trigBehavior, 
                        from = c("inserting proboscis", 
                                "flapping wings", 
                                "walking" ,
                                "drinking", 
                                "collecting pollen" , 
                                'grooming'), 
                        to = c("proboscis extended", 
                               "wings flapping", 
                               "wings not flapping, proboscis retracted", 
                               "proboscis extended", 
                               "wings not flapping, proboscis retracted", 
                               "wings not flapping, proboscis retracted"))

# use only field-observations of bumblebees
newDF <- newDF[newDF$vid.type == 'field' & newDF$pollinator == 'bumblebee', ]

# redefine legs to just front, mid, rear, and unknown
newDF <- within(newDF, 
                trL2 <- mapvalues(trigLeg, from = c('right front', 'left front', 
                                                    'left mid', 'right mid'), 
                                  to = c('front leg', 'front leg', 'mid leg', 'mid leg')))


# set order of levels
newDF <- within(newDF, 
                trigBehavior <- factor(trigBehavior, 
                                   levels=names(sort(table(trigBehavior), 
                                                     decreasing=TRUE))))

newDF <- within(newDF, 
                Beh2 <- factor(Beh2, 
                                       levels=names(sort(table(Beh2), 
                                                         decreasing=TRUE))))
colnames(newDF)
```


```{r, warning=FALSE}
quartz()
ggplot(newDF, aes(x = trigBehavior)) + 
     geom_bar()

quartz()
bb <- ggplot(newDF, aes(x = Beh2)) + 
     geom_bar() + 
     labs(x = "Behavior during pollen release") +  
     theme(legend.position = 'none') + 
     scale_fill_viridis(option = 'viridis', discrete = TRUE)
bb

ggplot(newDF, aes(x = 'Behavior that releases anther', fill = trigBehavior)) + 
     geom_bar() + 
     scale_fill_viridis(option = 'viridis', discrete = TRUE)



### bootstrap to get CI's (make a plot like bb)
vidnames = unique(newDF$Video)
behResamp <- function(o){
     # resample videos
     tmp = newDF[newDF$Video %in% sample(vidnames, replace = TRUE), c("Video", "Beh2") ]
     
     # resample behaviors within each video (if there's more than one)
     for(ii in names(table(tmp$Video))[table(tmp$Video) > 1]){
          tmp2 = tmp[tmp$Video == ii , ]
          tmp[tmp$Video == ii , ] =  tmp2[sample(1:nrow(tmp2), replace = TRUE), ]
     }
     
     pt = prop.table(table(tmp$Beh2))
     return(pt)
}


# should take about 30 seconds
system.time({
     beh_rep <- t(replicate(n = 10000, behResamp()))
})

colMeans(as.matrix(beh_rep))
# get 95% CI's
propTab3 <- data.frame(cbind(prop.table(table(newDF$Beh2)), 
                  t(apply(beh_rep, MARGIN = 2, 
                          quantile, c(0.025, 0.975)))))
colnames(propTab3) <- c('mean', "lower", "upper")
propTab3$Behavior <- rownames(propTab3)
propTab3 <- propTab3[propTab3$mean != 0 ,]

quartz()
ggplot(propTab3, aes(x = Behavior, y = mean)) + 
     #geom_point(size = 1, color= 'grey40') + 
     geom_pointrange(aes(ymax = upper, ymin=lower), size = 0.2) + 
     labs (x = "Behavior", y = "Proportion of bumblebee behaviors\nthat triggered anthers") +
     theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1), 
           axis.ticks.x=element_blank()) + 
     scale_x_discrete(labels=c("wings not flapping, proboscis retracted" = expression(
               paste("wings not flapping,\nproboscis retracted"))))
ggsave(filename = paste0(figDir,"Supp_BehaviorTrig.pdf"), width = 4, height = 4)
length(unique(newDF$Video)) # total number of bumblebee visits that we recorded that triggered an anther
nrow(newDF)
```



## See which leg of the bumblebee triggered the anther

```{r, cache = TRUE}
######################################################################
# Describe what leg triggered the anther (in bumblebees)
######################################################################


unique(newDF$trigLeg)

newDF <- within(newDF, 
                trigLeg <- factor(trigLeg, 
                               levels=names(sort(table(trigLeg), 
                                                 decreasing=TRUE))))

ggplot(newDF, aes(x = trigLeg)) + 
     geom_bar() + 
     labs(x = "What triggered the anther") +
     scale_fill_viridis(option = 'viridis', discrete = TRUE)



ggplot(newDF, aes(x = trL2)) + 
     geom_bar() + 
     labs(x = "What triggered the anther") + 
     scale_fill_viridis(option = 'viridis', discrete = TRUE)

table(newDF$trigLeg)  # counts for what leg triggered the thing
table(newDF$trL2)  # counts for what leg triggered the thing

# calculate CI's for proportions
### bootstrap to get CI's (make a plot like bb)
vidnames = unique(newDF$Video)
legResamp <- function(o){
     # resample videos
     tmp = newDF[newDF$Video %in% sample(vidnames, replace = TRUE), c("Video", "trL2") ]
     
     # resample behaviors within each video (if there's more than one)
     for(ii in names(table(tmp$Video))[table(tmp$Video) > 1]){
          tmp2 = tmp[tmp$Video == ii , ]
          tmp[tmp$Video == ii , ] =  tmp2[sample(1:nrow(tmp2), replace = TRUE), ]
     }
     tmp$trL2 <- factor(tmp$trL2, levels = c("front leg", "mid leg","unknown" ), ordered = TRUE)
     pt = prop.table(table(tmp$trL2))
     return(pt)
}


# should take about 30 seconds
system.time({
     leg_rep <- t(replicate(n = 10000, legResamp()))
})


colMeans(as.matrix(leg_rep))
# get 95% CI's
pt1 <- prop.table(table(newDF$trL2))
pt1 <- pt1[pt1 != 0]

propTab4 <- data.frame(cbind(pt1, 
                             t(apply(leg_rep, MARGIN = 2, 
                                     quantile, c(0.025, 0.975)))))
colnames(propTab4) <- c('mean', "lower", "upper")
propTab4$leg <- rownames(propTab4)
propTab4

propTab4$leg <- factor(propTab4$leg, levels = c('unknown', 'front leg', 'mid leg'))


# figure 4
quartz()
ggplot(propTab4, aes(x = leg, y = mean)) + 
     #geom_point(size = 1, color= 'grey40') + 
     geom_pointrange(aes(ymax = upper, ymin=lower), size = 0.2) + 
     labs (x = "Cause of anther release", 
           y = "Proportion of bumblebee causes\nthat triggered anthers") +
     theme(axis.text.x = element_text(angle = 30, hjust = 1, vjust = 1, colour = 'black'), 
           axis.ticks.x=element_blank()) + 
     ylim(c(0, 0.8))
ggsave(filename = paste0(figDir, "Supp_LegTrig.pdf"), width = 3, height = 4)
length(unique(newDF$Video))
nrow(newDF)
table(newDF$pollinator) #this analysis is only for bumblebees

# close all quartz windows
graphics.off()
```

## write data to files

```{r, eval = FALSE}
write.table(propTab, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table("\n",append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table(propTab2,append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table("\n",append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table(propTab3,append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table("\n",append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
write.table(propTab4,append = TRUE, '~/Desktop/proportions.csv', row.names = FALSE, sep = ", ")
```

